### ISSUE TITLE
games are not scaled down so large areas of the screen are obfuscated

### ISSUE THREAD

**Issue by halpz** [cosmo0/retropie-overlays-arcade-realistic#4]
is there a way to scale the emulation to fit these overlays, as a lot of my screen is being covered by the overlay image, or is this a bug? thanks!

**Comment by halpz** [comment]
i've installed via Arcade manager

**Comment by mike855** [comment]
Solution is aspect_ratioindex = 23 in common.cfg

**Comment by ghostface** [comment]
fyi some rom cfgs need to be fixed as well run this command to search/replace them in the roms folder:

sed -i 's/aspect_ratio_index = "22"/aspect_ratio_index = "23"/g' *.cfg

**Comment by cosmo0** [comment]
Files are fixed (it won't work with older RA installs but hey I can't do magic)
